routes/admin.php
<?php

Route::middleware(['admin'])
    ->namespace('Admin')
    ->group(function () {
        Route::get('/', 'UserController@index');
        Route::get('curriculums/lessons', 'CurriculumController@getLessons')->name('curriculums.lessons');
        Route::delete('curriculums/lessons/{id}', 'CurriculumController@detachLesson')->name('curriculums.lessons.detach');
        Route::get('questions/get-list', 'QuestionController@getList')->name('questions.get-list');
        Route::resources([
            'users'           => 'UserController',
            'teachers'        => 'TeacherController',
            'students'        => 'StudentController',
            'business'        => 'BusinessAreaController',
            'knowledge'       => 'KnowledgeAreaController',
            'knowledge-type'  => 'KnowledgeTypeController',
            'lessons'         => 'LessonController',
            'curriculums'     => 'CurriculumController',
            'curriculum-type' => 'CurriculumTypeController',
            'questions'       => 'QuestionController',
            'tests'           => 'TestController',
        ]);
        Route::get('questions-lessons', 'QuestionController@indexLession')->name('questions.lessons');
    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('student')
    ->as('student.')
    ->group(function () {
        require base_path('routes/student.php');
    });

Route::prefix('teacher')
    ->as('teacher.')
    ->group(function () {
        Route::middleware(['admin'])
            ->namespace('Teacher')
            ->group(function () {
                Route::get('{lessonId}/index','QuestionController@index')->name('index');
                Route::post('{lessonId}/create-essay-questions','QuestionController@createEssayQuestions')->name('create-essay-questions');
                Route::post('{lessonId}/create-choice-questions','QuestionController@createChoiceQuestions')->name('create-choice-questions');
                Route::get('{lessonId}/questions','QuestionController@listQuestions')->name('lesson.questions');
                Route::get('{lessonId}/lessons','QuestionController@listLessons')->name('lesson.lessons');
                Route::get('{lessonId}/add-wish-list','QuestionController@addWishList')->name('lesson.add-wish-list');
            });
    });


Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

app/Models/User.php
<?php

namespace App\Models;

use App\Presenters\UserPresenter;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laracodes\Presenter\Traits\Presentable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, Presentable;

    const USER_STATUS = [
        'Bình thường',
        'Đã nghỉ',
        'Tạm nghỉ'
    ];
    /**
     * @var string
     */
    const UPLOAD_DISK = 'public';

    /**
     * @var string
     */
    const AVATAR_DIR = 'upload/users/avatar';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone_number',
        'gender',
        'birthday',
        'role_id',
        'company',
        'department',
        'address',
        'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'name'         => 'required|min:2',
        'email'        => 'required|email|unique:users',
        'password'     => 'required|min:6',
        'phone_number' => 'required|unique:users',
        'gender'       => 'in:male,female',
        'birthday'     => 'nullable|date|before:today',
        'avatar'       => 'image',
        'address'      => 'nullable|min:5',
        'department'   => 'nullable|min:5',
        'company'      => 'nullable|min:5',
    ];


    protected $dates = ['birthday'];


    public function role(){
        return $this->belongsTo('App\Models\Role', 'role_id');
    }
    /**
     * The presenter class.
     *
     * @var string
     */
    protected $presenter = UserPresenter::class;

    public function userLesson()
    {
        return $this->hasMany('App\Models\UserLesson');
    }

    public function userLessonSub()
    {
        return $this->hasMany('App\Models\userLessonSub');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::with('role');
        $users = $users->when($request->name, function($q) use ($request){
            $q->where('name', 'like', '%' . $request->name . '%');
        });
        $users = $users->when($request->role, function($q) use ($request){
            $q->where('role_id',$request->role);
        });
        if($request->status && $request->status >= 0){
            $users = $users->where('status', $request->status);
        }
        $users = $users->paginate(10);
        $roles = Role::all()->pluck('name','id')->prepend(sprintf('-- %s --', 'Choose role'), 0);
        return view('admin.users.index', compact('users','roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.users.edit', $this->createOrEdit());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, User::$rules);

        $this->storeOrUpdate($request);

        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        return view('admin.users.edit', $this->createOrEdit($user));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

        $rules = User::$rules;
        $rules['email'] = [
            'email',
            Rule::unique('users')->ignore($user->id),
        ];
        $rules['phone_number'] = [
            Rule::unique('users')->ignore($user->id),
        ];
        if (!$request->password) {
            $rules['password'] = [];
        }
        $this->validate($request, $rules);

        $this->storeOrUpdate($request, $user);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {

        $user->delete();

        if (request()->ajax()) {
            return response()->json([
                'message'  => '',
                'redirect' => true,
            ]);
        }

        return redirect()->route('admin.users.index');
    }

    /**
     * Create or edit a user.
     *
     * @param  \App\Models\User|null $user
     * @return array
     */
    protected function createOrEdit(User $user = null)
    {
        $user = $user ?: new User;
        $url  = $user->id
        ? route('admin.users.update', [$user->id])
        : route('admin.users.store');
        $roles = Role::all()->pluck('name','id');

        return compact('user', 'url', 'roles');
    }

    /**
     * Store or update a user.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\User|null $user
     * @return \App\Models\User
     */
    protected function storeOrUpdate(Request $request, User $user = null)
    {
        $user = $user ?: new User;
        $data = $request->all();
        
        $user->fill($data);
        if ($request->password) {
            $user->password = bcrypt($request->password);
        }
        if ($request->hasFile('avatar')) {
            $user->avatar = $request->file('avatar')->storePublicly(User::AVATAR_DIR, User::UPLOAD_DISK);
        }

        $user->save();

        return $user;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Repository\UserRepository;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $user;
    function __construct(UserRepository $user)
    {
        $this->user = $user;

    }

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }


}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('title', $user->id ? 'Sửa thông tin người dùng' : 'Thêm mới người dùng')

@section('content_header')
<h1>{{ $user->id ? 'Sửa thông tin' : 'Thêm mới' }} người dùng</h1>

@stop

@section('content')

<div class="box">
        {{-- <div class="box-title">
            <h4>Sửa thông tin học sinh {{$student->name}}</h4>
        </div> --}}
        @include('partials.errors')
        <div class="box-body">
            {!! Form::model($user, [
                'url' => $url,
                'role' => 'form',
                'method' => $user->id ? 'PUT' : 'POST',
                'files' => true,
            ])
            !!}
            <div class="row">
                <div class="col-md-3 text-center">

                        <img src="{{ $user->present()->avatar('square256') }}" class="img-responsive" />

                        {!! Form::file('avatar', [
                            'class' => 'form-control',
                        ]) !!}
                        <br>
                        <div class="form-group m-t-lg">
                            {!! Form::submit('Lưu', ['class' => 'btn btn-success']) !!}
                        </div>
                    </div>
                <div class="col-md-9">
                    <div class="form-group col-md-6">
                        {!!  Form::label('name', 'Họ tên: ') !!}
                        {!!  Form::text('name', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('password', 'Mật khẩu: ') !!}
                        {!!  Form::password('password', ['class' => 'form-control', 'placeholder' => 'Để trống nếu không thay đổi']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('phone_number', 'SDT: ') !!}
                        {!!  Form::text('phone_number', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('gender', 'Giới tính: ') !!}
                        {!!  Form::select('gender', ['male' => 'Nam', 'female' => 'Nữ'], 'male', ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('birthday', 'Ngày sinh: ') !!}
                        {!!  Form::date('birthday', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('email', 'Email: ') !!}
                        {!!  Form::text('email', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('address', 'Địa chỉ: ') !!}
                        {!!  Form::text('address', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('department', 'Bộ phận làm việc: ') !!}
                        {!!  Form::text('department', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('company', 'Công ty: ') !!}
                        {!!  Form::text('company', null, ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::label('role', 'Loại người dùng') !!}
                        {!!  Form::select('role_id', $roles, \App\Models\Role::ROLE_STUDENT , ['class' => 'form-control']) !!}
                    </div>
                    <div class="form-group col-md-6">
                        {!!  Form::checkbox('status') !!}
                        {!!  Form::label('status', 'Kích hoạt') !!}
                    </div>
                </div>
            </div>

            {{-- {!! Form::submit('Lưu', ['class'=>'btn btn-success clear-both']) !!} --}}
            {!! Form::close() !!}
        </div>
    </div>
    
    @stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Quản lý người dùng')
@section('css')
    @parent
    {!! Html::style('css/style.css') !!}
@stop
@section('content_header')
    <h1>Quản lý người dùng</h1>
    <ul class="list-inline">
        <a href="{{ route('admin.users.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Thêm mới</a>
    </ul>
    @if(session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
@stop

@section('content')
    <div class="row" id="admin">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Người dùng</h3>
                    <div class="box-tools">
                        {!! Form::open(['route' => 'admin.users.index', 'method'=>'GET','class' => 'form-inline']) !!}
                        <div >
                            <input type="text" name="name" class="form-control" placeholder="Tên" value="{{ request('name') }}">
                            {!!  Form::select('role', $roles, request('role') , ['class' => 'form-control']) !!}
                            {!! Form::select(
                                'status', 
                                ['-1' => '-- Status --', '0' => 'Inactive', '1' => 'Active' ], 
                                request('status'),
                                ['class' => 'form-control']
                           ) !!}
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Status</th>
                            <th>Avatar</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr id="brand-{{$user->id}}">
                                <td class="brand-id">{{$user->id}}</td>
                                <td>{!! $user->present()->status !!}</td>
                                <td>
                                    <img src="{{ $user->present()->avatar('square64') }}">
                                </td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->phone_number }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->role->name }}</td>
                                <td style="min-width: 100px">
                                    <a data-toggle="tooltip" class="btn btn-sm btn-primary" title="Edit" href="{{ route('admin.users.edit', $user->id) }}"><i class="fa fa-pencil"></i></a>
                                    <a href="{{ route('admin.users.destroy', $user->id) }}"
                                        class="btn btn-sm btn-danger" title="Delete"
                                        data-swal="{{ json_encode(swal([
                                            'title' => 'Are you sure',
                                            'type' => 'question',
                                            'showCancelButton' => true,
                                        ])) }}"
                                        data-swal-method="DELETE"><i class="fa fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="text-right">
                    {{ $users->appends(request()->query())->links() }}
                </div>
                </div>
            </div>
        </div>
    </div>

@stop