routes/admin.php
<?php

Route::middleware(['admin'])
    ->namespace('Admin')
    ->group(function () {
        Route::get('/', 'UserController@index');
        Route::get('curriculums/lessons', 'CurriculumController@getLessons')->name('curriculums.lessons');
        Route::delete('curriculums/lessons/{id}', 'CurriculumController@detachLesson')->name('curriculums.lessons.detach');
        Route::get('questions/get-list', 'QuestionController@getList')->name('questions.get-list');
        Route::resources([
            'users'           => 'UserController',
            'teachers'        => 'TeacherController',
            'students'        => 'StudentController',
            'business'        => 'BusinessAreaController',
            'knowledge'       => 'KnowledgeAreaController',
            'knowledge-type'  => 'KnowledgeTypeController',
            'lessons'         => 'LessonController',
            'curriculums'     => 'CurriculumController',
            'curriculum-type' => 'CurriculumTypeController',
            'questions'       => 'QuestionController',
            'tests'           => 'TestController',
        ]);
        Route::get('questions-lessons', 'QuestionController@indexLession')->name('questions.lessons');
    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('student')
    ->as('student.')
    ->group(function () {
        require base_path('routes/student.php');
    });

Route::prefix('teacher')
    ->as('teacher.')
    ->group(function () {
        Route::middleware(['admin'])
            ->namespace('Teacher')
            ->group(function () {
                Route::get('{lessonId}/index','QuestionController@index')->name('index');
                Route::post('{lessonId}/create-essay-questions','QuestionController@createEssayQuestions')->name('create-essay-questions');
                Route::post('{lessonId}/create-choice-questions','QuestionController@createChoiceQuestions')->name('create-choice-questions');
                Route::get('{lessonId}/questions','QuestionController@listQuestions')->name('lesson.questions');
                Route::get('{lessonId}/lessons','QuestionController@listLessons')->name('lesson.lessons');
                Route::get('{lessonId}/add-wish-list','QuestionController@addWishList')->name('lesson.add-wish-list');
            });
    });


Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laracodes\Presenter\Traits\Presentable;
use App\Presenters\CommonPresenters;

class Question extends Model
{
    use Notifiable, SoftDeletes, Presentable;

    protected $fillable = [
        'lesson_id',
        'type',
        'code',
        'content',
        'preview_flg',
        'number_of_ans',
        'answer_type',
        'image',
        'url_video',
        'level',
        'question_type',
        'approve_flg',
        'apply_flg',
        'created_by'
    ];

    public function getImagelAttribute($value){
        return asset('/storage/questions').'/'.$this->id.'/'.$value;
    }

    /**
     * Bài học
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lesson(){
        return $this->belongsTo('App\Models\Lesson', 'lesson_id');
    }

    /**
     * Người tạo
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creater(){
        return $this->belongsTo('App\Models\User', 'created_by');
    }

    /**
     * Người tạo
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function answers(){
        return $this->hasMany(Answer::class);
    }

    protected $presenter = CommonPresenters::class;
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Config;
use App\Repository\LessonsRepository;
use App\Repository\QuestionRepository;
use App\Models\KnowledgeArea;
use App\Models\KnowledgeType;
use App\Models\Question;

class QuestionController extends Controller
{

    private $question;
    private $lessons;

    function __construct(QuestionRepository $question,
                         LessonsRepository $lessons
    )
    {
        $this->question = $question;
        $this->lessons = $lessons;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $input = Input::get();
        $knowledgeAreas = KnowledgeArea::all()->pluck('name', 'id');
        $knowledgeTypes = KnowledgeType::all()->pluck('name', 'id');
        $level = Config::get('constant.LEVEL');
        $questionCate = Config::get('constant.QUESTION_CATE');
        $questionType = Config::get('constant.QUESTION_TYPE');
        $questionApprove = Config::get('constant.QUESTION_APPROVE');
        $questionApply = Config::get('constant.QUESTION_APPLY');

        $questions = $this->question->findQuestions($input, ITEM_PER_PAGE);
        return view('admin.question.index',
            compact('questions',
                'knowledgeAreas',
                'knowledgeTypes',
                'questionCate',
                'questionType',
                'questionApprove',
                'questionApply',
                'level'
            ));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexLession()
    {
        $input = Input::get();
        $knowledgeAreas = KnowledgeArea::all()->pluck('name', 'id');
        $knowledgeTypes = KnowledgeType::all()->pluck('name', 'id');
        $lessonType = Config::get('constant.LESSON_TYPE');
        $level = Config::get('constant.LEVEL');
        $status = Config::get('constant.STATUS');
        $lessons = $this->lessons->findLessons($input, ITEM_PER_PAGE);
        return view('admin.question.lessons',
            compact('lessons',
                'knowledgeAreas',
                'knowledgeTypes',
                'lessonType',
                'level',
                'status'
            ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * get list question
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function getList(Request $request){
        $input = Input::get();
        $questions = $this->question->findQuestions($input, ITEM_PER_PAGE);
        return $questions->toJson();
    }
}

app/Http/Controllers/Teacher/QuestionController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Http\Controllers\Controller;
use App\Http\Requests\QuestionRequest;
use App\Models\Answer;
use App\Models\Lesson;
use App\Models\Question;
use App\Models\Role;
use App\Models\User;
use App\Models\WishList;
use App\Repository\AnswerRepository;
use App\Repository\LessonsRepository;
use App\Repository\QuestionRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;

class QuestionController extends Controller
{
    private $question;
    private $answer;
    private $lesson;

    public function __construct(QuestionRepository $question,
        AnswerRepository $answer,
        LessonsRepository $lesson) {
        $this->question = $question;
        $this->answer   = $answer;
        $this->lesson   = $lesson;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $lessonId = $request->lessonId;
        $lesson   = $this->lesson->findOrFail($lessonId);
        //$questionEssay = $lesson->questions(Q_ESSAY)->paginate();
        $questions        = $lesson->questions()->with('creater', 'answers')->paginate();
        $questionType     = Config::get('constant.QUESTION_TYPE');
        $questionlevels   = collect(Config::get('constant.LEVEL'));
        $questionapproves = collect(Config::get('constant.QUESTION_APPROVE'));
        $questionapplies  = collect(Config::get('constant.QUESTION_APPLY'));

        $wishList = WishList::where('user_id', user()->id)->get()->pluck('lesson_id')->toArray();
        $admins = User::where('role_id', Role::ROLE_ADMIN)->get()->pluck('name', 'id');

        $lessonLists = Lesson::with('knowledgeArea','questionsEssay','questionsChoice', 'questionsEssayUser','questionsChoiceUser')->where('is_test', 0)
            ->when($request->lesson_name, function ($q) use ($request) {
                $q->where('name', 'like', '%' . $request->lesson_name . '%');
            })
            ->paginate();
        $srcDelete = asset('teacher/img/icon24.png');
        $srcAdd = asset('teacher/img/icon21.png');

        return view('teacher.index', compact('questionType', 'lesson', 'lessonId', 'questions', 'admins', 'questionlevels', 'questionapproves', 'questionapplies', 'wishList', 'lessonLists', 'srcDelete', 'srcAdd'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function createEssayQuestions(QuestionRequest $request)
    {
        $lessonId = $request->lessonId;
        $userId   = Auth::id();
        // create question
        $dataQuestion = [
            'lesson_id'     => $lessonId, // đang lấy mặc định Bài học có id 1, bổ sung khi có màn hình list bài học và giáo viên
            'code'          => 'TL' . get_unique_code(),
            'type'          => $request->get('type'),
            'preview_flg'   => $request->has('preview_flg') ? $request->get('preview_flg') : Q_NO_PREVIEW,
            'content'       => $request->get('content'),
            'image'         => $request->get('image'),
            'level'         => $request->get('level'),
            'question_type' => $request->get('question_type'),
            'created_by'    => $userId,
        ];
        $question = $this->question->insert($dataQuestion);
        $this->question->saveFile($request, $question);

        // insert answer
        $dataAnswer = [
            'question_id' => $question->id,
            'content'     => $request->get('answer'),
            'correct_flg' => A_IS_CORRECT,
            'created_by'  => $userId,
        ];
        $answer = $this->answer->insert($dataAnswer);

        $request->flush();
        return redirect(route('teacher.index', $lessonId));
    }

    public function createChoiceQuestions(QuestionRequest $request)
    {
        $lessonId = $request->lessonId;
        $userId   = Auth::id();
        // create question
        $dataQuestion = [
            'lesson_id'     => $lessonId, // đang lấy mặc định Bài học có id 1, bổ sung khi có màn hình list bài học và giáo viên
            'code'          => 'TN' . get_unique_code(),
            'type'          => $request->get('type'),
            'preview_flg'   => $request->has('preview_flg') ? $request->get('preview_flg') : Q_NO_PREVIEW,
            'number_of_ans' => $request->get('number_of_ans'),
            'answer_type'   => $request->get('answer_type'),
            'content'       => $request->get('content_choice'),
            'level'         => $request->get('level'),
            'question_type' => $request->get('question_type'),
            'created_by'    => $userId,
        ];
        $question = $this->question->insert($dataQuestion);

        // insert answer
        foreach ($request->get('answer') as $k => $answer) {
            $dataAnswer = [
                'question_id' => $question->id,
                'content'     => $answer,
                'correct_flg' => $request->get('correct_flg')[$k],
                'created_by'  => $userId,
            ];

            $answer = $this->answer->insert($dataAnswer);
            if (!empty($request->image_ans[$k])) {
                $this->answer->saveFile($request->image_ans[$k], $answer);
            }
        }

        $request->flush();
        return redirect(route('teacher.index', $lessonId));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * get list question
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $lessonId
     * @return \Illuminate\Http\Response
     */

    public function listQuestions(Request $request, $lessonId)
    {

        $lesson    = $this->lesson->findOrFail($lessonId);
        $questions = Question::where('lesson_id', $lessonId);
        if ($request->admin > 0) {
            $questions = $questions->where('created_by', $request->admin);
        }
        if ($request->questionLevel > -1) {
            $questions = $questions->where('level', $request->questionLevel);
        }
        if ($request->questionapprove > -1) {
            $questions = $questions->where('approve_flg', $request->questionapprove);
        }
        if ($request->questionapply > -1) {
            $questions = $questions->where('apply_flg', $request->questionapply);
        }
        $questions = $questions->with('creater', 'answers')->paginate();

        return $questions->toJson();
    }

    /**
     * get list lesson
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $lessonId
     * @return \Illuminate\Http\Response
     */

    public function listLessons(Request $request, $lessonId)
    {

        $lessons = Lesson::with('knowledgeArea')
            ->when($request->name, function ($q) use ($request) {
                $q->where('name', 'like', '%' . $request->name . '%');
            })
            ->paginate();

        return $lessons->toJson();
    }

    public function addWishList(Request $request){
        if (!isset($request->lessonAddId)) {
            abort(500);
        }
        $lessonAddId = $request->lessonAddId;
        $wishList = WishList::where('user_id', user()->id)->where('lesson_id',$lessonAddId)->first();

        if($wishList){
            $wishList->delete();
            return [
                'success' => true,
                'action' => 'delete'
            ];
        } else{
            $newWishList = new WishList();
            $newWishList->user_id = user()->id;
            $newWishList->lesson_id = $lessonAddId;
            $newWishList->save();
            return [
                'success' => true,
                'action' => 'add'
            ];
        }
    }
}

resources/views/admin/question/index.blade.php
@extends('adminlte::page')

@section('title', 'Quản lý câu hỏi')

@section('css')
    {!! Html::style('css/style.css') !!}
@stop

@section('content_header')
    <h1>Danh sách câu hỏi</h1>
    <ul class="list-inline">
        <div class="btn-group ">
            <select class="btn btn-primary" onchange="this.options[this.selectedIndex].value && (window.location = this
            .options[this.selectedIndex].value);">
                <option value="{{url(route('admin.questions.index'))}}">Lọc theo câu hỏi</option>
                <option value="{{url(route('admin.questions.lessons'))}}">Lọc theo bài học</option>
            </select>
        </div>
    </ul>
    @if(session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    {!! Form::open(['route' => 'admin.questions.index', 'method'=>'GET']) !!}
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="input-group-sm">
                                {!! Form::select('k_area', $knowledgeAreas, null, ['class' => 'form-control',
                                'placeholder' => '--Lĩnh vực kiến thức--'
                                ]) !!}
                            </div>
                        </div>
                        <div class="col-sm-2" style="margin-left: -25px;">
                            <div class="input-group-sm">
                                {!! Form::select('k_type', $knowledgeTypes, null, ['class' => 'form-control',
                                'placeholder' => '--Loại kiến thức--'
                                ]) !!}
                            </div>
                        </div>

                        <div class="col-sm-2" style="margin-left: -25px;">
                            <div class="input-group-sm">
                                {!! Form::select('type', $questionCate, null, ['class' => 'form-control',
                                'placeholder' => '--Thể loại--']) !!}
                            </div>
                        </div>
                        <div class="col-sm-2" style="margin-left: -25px;">
                            <div class="input-group-sm" style="width: 65%;">
                                {!! Form::select('level', $level, null, ['class' => 'form-control',
                                'placeholder' => '--Cấp độ--']) !!}
                            </div>
                        </div>
                        <div class="col-sm-2" style="margin-left: -77px;">
                            <div class="input-group-sm" style="width: 65%;">
                                {!! Form::select('q_type', $questionType, null, ['class' => 'form-control',
                                'placeholder' => '--Kĩ năng--']) !!}
                            </div>
                        </div>
                        <div class="col-sm-2 pull-right">
                            <div class="input-group-sm">
                                {!! Form::select('apply', $questionApply, null, ['class' => 'form-control',
                                'placeholder' => '--Trạng thái áp dụng--']) !!}
                            </div>
                        </div>
                        <div class="pull-right">
                            <div class="input-group-sm">
                                {!! Form::select('approve', $questionApprove, null, ['class' => 'form-control',
                                'placeholder' => '--Trạng thái duyệt--']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-top: 15px;">
                        <div class="col-sm-12">
                            <div class="input-group input-group-sm">

                                {!! Form::text('content', null, ['class' => 'form-control', 'placeholder' => 'Tìm kiếm']) !!}
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <div class="box-body">
                    @if($questions->count() > 0)
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" class="iCheckTable" id="checkAll"></th>
                                <th>Mã câu hỏi</th>
                                <th>Nội dung</th>
                                <th>Thể loại</th>
                                <th>Độ khó</th>
                                <th>Kĩ năng</th>
                                <th>Thuộc bài học</th>
                                <th>Trạng thái duyệt</th>
                                <th>Trạng thái áp dụng</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($questions as $question)
                                <tr id="brand-{{$question->id}}">
                                    <td><input type="checkbox" class="iCheckTable iCheckItem"
                                               value="{{ $question->id }}">
                                    </td>
                                    <td><a href="{{url(route('admin.lessons.edit', $question->id)) }}">{{ $question->code }}</a></td>
                                    <td>{!! $question->content !!}</td>
                                    <td>{{ $questionCate[$question->type] }}</td>
                                    <td>{!! $question->present()->level !!}</td>
                                    <td>{{ $questionType[$question->question_type] }} </td>
                                    <td>{{ $question->lesson->code }} </td>
                                    <td>{!! $question->present()->approve !!}</td>
                                    <td>{!! $question->present()->apply !!}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="pull-right">
                            {{ $questions->appends(Request::all())->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/question/lessons.blade.php
@extends('adminlte::page')

@section('title', 'Quản lý câu hỏi')

@section('css')
    {!! Html::style('css/style.css') !!}
@stop

@section('content_header')
    <h1>Danh sách câu hỏi</h1>
    <ul class="list-inline">
        <div class="btn-group ">
            <select class="btn btn-primary" onchange="this.options[this.selectedIndex].value && (window.location = this
            .options[this.selectedIndex].value);">
                <option value="{{url(route('admin.questions.lessons'))}}">Lọc theo bài học</option>
                <option value="{{url(route('admin.questions.index'))}}">Lọc theo câu hỏi</option>
            </select>
        </div>
    </ul>
    @if(session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    {!! Form::open(['route' => 'admin.questions.lessons', 'method'=>'GET']) !!}
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="input-group-sm">
                                {!! Form::select('knowledge_area_id', $knowledgeAreas, null, ['class' => 'form-control',
                                'placeholder' => '--Lĩnh vực kiến thức--'
                                ]) !!}
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="input-group-sm">
                                {!! Form::select('knowledge_type', $knowledgeTypes, null, ['class' => 'form-control',
                                'placeholder' => '--Loại kiến thức--'
                                ]) !!}
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="input-group-sm">
                                {!! Form::select('level', $level, null, ['class' => 'form-control',
                                'placeholder' => '--Cấp độ--']) !!}
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="input-group-sm">
                                {!! Form::select('type', $lessonType, null, ['class' => 'form-control',
                                'placeholder' => '--Định dạng--']) !!}
                            </div>
                        </div>
                        <div class="col-sm-2 pull-right">
                            <div class="input-group-sm">
                                {!! Form::select('status', $status, null, ['class' => 'form-control',
                                'placeholder' => '--Trạng thái duyệt--']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-top: 15px;">
                        <div class="col-sm-12">
                            <div class="input-group input-group-sm">

                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Tìm kiếm']) !!}
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <div class="box-body">
                    @if($lessons->count() > 0)
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th><input type="checkbox" class="iCheckTable" id="checkAll"></th>
                                <th>Mã bài học</th>
                                <th>Tên bài học</th>
                                <th>Định dạng</th>
                                <th>Loại kiến thức</th>
                                <th>Lĩnh vực kiến thức</th>
                                <th>Cấp độ</th>
                                <th>Trạng thái duyệt</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($lessons as $lesson)
                                <tr id="brand-{{$lesson->id}}">
                                    <td><input type="checkbox" class="iCheckTable iCheckItem"
                                               value="{{ $lesson->id }}">
                                    </td>
                                    <td>{{ $lesson->code }}</td>
                                    <td>
                                        <a href="{{url(route('teacher.index', $lesson->id))
                                        }}">{{$lesson->name}}</a>
                                    </td>
                                    <td>{{ $lesson->type }}</td>
                                    <td>{{ $lesson->knowledgeType->name }}</td>
                                    <td>{{ $lesson->knowledgeArea->name }}</td>
                                    <td>{!! $lesson->present()->level !!}</td>
                                    <td>{!! $lesson->present()->status !!}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="pull-right">
                            {{ $lessons->appends(Request::all())->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@stop